[package]
name = "demo"
version = "0.1.0"
authors = ["fortunewang <fortunewang@qq.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
cqrs = { path = "../cqrs" }

[lib]
name = "demo"
crate-type = ["cdylib"]
